### ISSUE TITLE
[REQUEST] Allow 'docker attach' for console

### ISSUE THREAD

**Issue by 4325123** [IMetZach/bedrock-server#9]
On some other minecraft docker instances, you can connect to the minecraft console by way of issuing 'docker attach <container id>'.  It could be that I'm missing something, but I can't seem to locate a way to attach to the console.  It's nice to get in to add people to a whitelist or op, instead of trying to figure out the file and the UUID number.

**Comment by IMetZach** [comment]
Well the script to start the container will create a directory in ```${HOME}/local/minecraft/``` that contains your server files and world data so you can edit them. To connect to the console inside the container, I'll need to add the telnet client to the image.

**Comment by 4325123** [comment]
> Well the script to start the container will create a directory in `${HOME}/local/minecraft/` that contains your server files and world data so you can edit them. To connect to the console inside the container, I'll need to add the telnet client to the image.

I'm not 100% familiar with bedrock server.  Does the bedrock server allow you to telnet into a console port?  If this is the case, I could just map the port and connect to it with a linux server.

**Comment by IMetZach** [comment]
This container is for the Bedrock Edition of MineCraft, not the java version. You can learn more about the [Bedrock Edition here](https://help.minecraft.net/hc/en-us/articles/360035131651-Dedicated-Servers-for-Minecraft-on-Bedrock-).

**Comment by 4325123** [comment]
> This container is for the Bedrock Edition of MineCraft, not the java version. You can learn more about the [Bedrock Edition here](https://help.minecraft.net/hc/en-us/articles/360035131651-Dedicated-Servers-for-Minecraft-on-Bedrock-).

Thanks for the response.  I understand it's the bedrock version, which is the one I want, so I can use it as a server for ipad minecraft clients.  Maybe let me start over with the issue I'm having and you may already have a solution for me.  I don't mean for this to be minecraft support but you may had run into this issue and have an alternative solution.

I'd like to use the whitelist function, but the whitelist function in the minecraft client gui is broke.  The other option is to use the console to see who's trying to login, then add them to the whitelist from the console.  Another option is to use some web site to lookup the xuid of the user and put that in the whitelist.json file and restart the docker instance.  

It would be nice to somehow get into the console of the bedrock server so that we can run these commands on the console.  You mentioned telnet, so I'm wondering if there maybe is a console port open I can telnet into to do this and I just didn't know about it.  Thanks!

**Comment by IMetZach** [comment]
Hey. Sorry for the late response. I'm working on getting the container updated to make it easy to attach to it and view the console. If you just want to look up the XUID for your white list, you can view the logs. I've been testing on Podman instead of Docker but the command I use is:

```
podman container logs <server name>
```
or if I want to continue viewing the logs in real time I use:  

```
podman container logs -f <server name>
``` 
From their [documentation](https://docs.docker.com/engine/reference/commandline/container_logs/) it looks like in Docker you would use:  

```
docker container logs <server name>
```

**Comment by IMetZach** [comment]
Ok. I figured it out. I updated the launch script to add the ```-it``` flag to container creation. Once it's up and running you can then do ```docker attach <server name>``` to connect and I found that using a / in front of the commands throws an error. So instead of ```/gamerule``` instead just use ```gamerule```. Once you're done and want to exit, the Docker default to leave is:

```
ctrl+p ctrl+q
```

If you exit any other way it will stop the container.
